name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Install Valgrind for tests
      run: sudo apt install valgrind
    - name: tests
      run: TMPDIR="/tmp" ./build/tests -v
