#!/bin/bash

if [[ -z $IDEA_LOCAL_PATH ]]; then
    IDEA_LOCAL_PATH="$HOME/.local/share/idea"
fi
TODO_LIST_BIN=$IDEA_LOCAL_PATH/todos.bin

# Source: https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
IDEA_EXE_PATH="$SCRIPT_DIR/idea"

SCRIPT_DATA_PATH="$IDEA_LOCAL_PATH/scripts_data/auto_export_html"
INDEX_PATH="$SCRIPT_DATA_PATH/index.html"
GENERATED_HTML_PATH="$SCRIPT_DATA_PATH/generated.html"

HTML_REDIRECT_SEC=1
JS_REDIRECT_MSEC=500
INDEX_HTML="
<!DOCTYPE html>
<html>
    <head>
        <!-- Source: https://stackoverflow.com/a/5411567 -->
        <meta http-equiv=\"refresh\" content=\"$HTML_REDIRECT_SEC; url=./generated.html\" />

        <title>idea</title>
        <link rel=\"icon\" type=\"image/png\" href=\"data:image/png;base64,$ICON_BASE64\">

        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">

        <style>
            /* Colors taken from <https://tsoding.github.io/schedule/> */
            :root {
                --bg: #181818;
                --bg-light: #1b1b1b;

                --fg: #e4e4ef;
                --fg-dark: #515151;

                --green: #73c936;
            }

            body {
                background: var(--bg);
                color: var(--fg);
            }

            header {
                background: var(--bg);

                position: sticky;
                top: 0px;
            }

            h1 {
                text-align: center;
                color: var(--green);
            }

            h2 {
                font-size: 22px;
                text-align: center;
                margin-bottom: 0px;
            }

            p {
                text-align: center;
            }

            a {
                text-decoration: none;
                color: var(--green);
                border-bottom: 1px solid;
            }
        </style>
    </head>

    <body>
        <header>
            <h1>idea</h1>
            <hr>
        </header>

        <main>
            <h2>Generating...</h2>
            <p id=\"redirect_text\">If the browser doesn't redirect you, please <a href=\"generated.html\">click here</a></p>
        </main>
    </body>
    <script>
        redirect_text.style.display = \"none\"

        // If JS is available redirect it faster than HTML refresh that only accepts seconds
        setTimeout(() => {
            window.location.replace(\"./generated.html\");
        }, $JS_REDIRECT_MSEC)

        setTimeout(() => {
            redirect_text.style.display = \"revert\"
        }, $HTML_REDIRECT_SEC * 1000 + 200)
    </script>
</html>
"

help() {
    echo "-h, --help ......... Help"
    echo "--daemon ........... Run daemon"
}

export_html() {
    IDEA_OUTPUT=$(IDEA_LOCAL_PATH="$IDEA_LOCAL_PATH" $IDEA_EXE_PATH "html $GENERATED_HTML_PATH")
    if [[ $? -ne 0 ]]; then
        rm "$GENERATED_HTML_PATH"
        echo "[ERROR] Error while exporting to HTML: $IDEA_OUTPUT"
    fi
    echo "[INFO] Exported HTML from idea at $(date) ($(date '+%s'))"
}

########

if [[ ! -d "$IDEA_LOCAL_PATH" ]]; then
  echo "[ERROR] $IDEA_LOCAL_PATH doesn't exists. Run idea for the first time to create that directory"
  exit 1
fi

# Source: https://stackoverflow.com/a/677212
if ! command -v "$IDEA_EXE_PATH" >/dev/null 2>&1; then
    echo "[ERROR] Unable to find or execute $IDEA_EXE_PATH"
    exit 1
fi

mkdir -p "$SCRIPT_DATA_PATH"

if [[ $# -eq 0 ]]; then
    help
    exit 1

elif [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
    help

elif [[ $1 == "--daemon" ]]; then
    echo "$INDEX_HTML" > "$INDEX_PATH"

    echo "[INFO] Running idea_auto_export_html daemon for $IDEA_LOCAL_PATH"

    while [[ true ]]; do
        inotifywait -e access "$INDEX_PATH" &> /dev/null

        echo "[INFO] index.html opened at $(date) ($(date '+%s'))"

        if [[ ! -e "$TODO_LIST_BIN" ]] || [[ ! -e "$GENERATED_HTML_PATH" ]]; then
            export_html

        else
            # Source: https://askubuntu.com/a/803151
            TODO_LIST_MTIME=$(stat -c '%Y' "$TODO_LIST_BIN")
            GENERATED_MTIME=$(stat -c '%Y' "$GENERATED_HTML_PATH")

            if [[ $TODO_LIST_MTIME -ge $GENERATED_MTIME ]]; then
                export_html
            fi
        fi

        sleep 1
    done
else
    echo "[ERROR] Unknown command '$1'"
    exit 1
fi
