#!/bin/bash

# Thanks to <https://www.youtube.com/watch?v=CPjOLq2FjsQ> for an introduction in this topic

function _idea {
    local AVAILABLE_COMMANDS="
        <c>
            COMMAND_LIST(todo_list_functionality, todo_list_functionality_count);
            COMMAND_LIST(cli_functionality, cli_functionality_count);
        </c>
    "

    COMPREPLY=()

    CURRENT_WORD="${COMP_WORDS[COMP_CWORD]}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        local CURRENT_WORD=$CURRENT_WORD
        COMPREPLY=($( compgen -W "$AVAILABLE_COMMANDS" -- $CURRENT_WORD ))
    else
        PARAMS=()
        case "${COMP_WORDS[1]}" in
            <c>COMMAND_SWITCH(todo_list_functionality, todo_list_functionality_count)</c>
            <c>COMMAND_SWITCH(cli_functionality, cli_functionality_count)</c>
        esac

        for PARAM in "${PARAMS[@]}"; do
            REPEAT_LAST_PARAMETER="" # for the token "[...]" (infinite arguments)
            MATCHED=true
            read -ra PARAM_WORDS <<< "$PARAM"

            # Check if the parameters and arguments previous to the current
            # position match
            for ((i=2; i<$COMP_CWORD; i++)); do
                PARAM_WORD=${PARAM_WORDS[$i-2]}
                WORD=${COMP_WORDS[$i]}

                if [[ -z $PARAM_WORD ]]; then
                    if [[ -z $REPEAT_LAST_PARAMETER ]]; then MATCHED=false; fi
                    break;
                fi

                if [[ "$PARAM_WORD" == "[...]" ]]; then
                    REPEAT_LAST_PARAMETER=${PARAM_WORDS[$i-3]} # Take the previous one
                    break;
                fi

                # We don't check if the token is ok. We could, but it is a little expensive...
                if [[ "$PARAM_WORD" != \[*\] ]]; then # If it is NOT a token
                    if [[ "$WORD" != "$PARAM_WORD" ]]; then
                        MATCHED=false
                        break;
                    fi
                fi
            done

            if $MATCHED; then
                if [[ -z $REPEAT_LAST_PARAMETER ]]; then
                    NEXT=${PARAM_WORDS[$COMP_CWORD-2]}
                    if [[ "$NEXT" == "[...]" ]]; then NEXT=${PARAM_WORDS[$COMP_CWORD-3]}; fi
                else
                    NEXT=$REPEAT_LAST_PARAMETER
                fi

                if [[ -z "$NEXT" ]] \
                   || [[ "$NEXT" == "[text]" ]] \
                   || [[ "$NEXT" == "[name]" ]] \
                   || [[ "$NEXT" == "[new_name]" ]] \
                   || [[ "$NEXT" == "[new_position]" ]] \
                   || [[ "$NEXT" == "[index]" ]];
               then
                    COMPREPLY+=() # Nothing
                elif [[ "$NEXT" == "[path]" ]]; then
                    COMPREPLY+=( * )
                elif [[ "$NEXT" == "[tag_name]" ]]; then
                    mapfile -t TAGS < <(
                        IDEA_CLI_DISABLE_COLORS=true "${COMP_WORDS[0]}" tags | tail -n +2 | sed 's/    # //g' # Get tags from idea
                    )

                    for TAG in "${TAGS[@]}"; do
                        if [[ $TAG == "$CURRENT_WORD"* ]]; then COMPREPLY+=("$TAG"); fi
                    done
                elif [[ "$NEXT" == "[todo]" ]]; then
                    mapfile -t TODOS < <(
                        IDEA_CLI_DISABLE_COLORS=true "${COMP_WORDS[0]}" list | sed 's/^[0-9]) \(N \)\?//g'  # Get ToDos from idea
                    )

                    for TODO in "${TODOS[@]}"; do
                        if [[ $TODO == "$CURRENT_WORD"* ]]; then COMPREPLY+=("$TODO"); fi
                    done
                else
                    COMPREPLY+=("$NEXT")
                fi
            fi
        done
    fi
}

complete -F _idea idea
