#include <ncurses.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "parser.h"
#include "utils/list.h"
#include "todo_list.h"

List todo_list = list_new();
bool todo_list_modified = false;

bool export_template(FILE * file) {
  if (!file) return false;
  if (fprintf(file, "-- File generated by idea. Edit this file with caution.\n") <= 0) return false;
  if (fprintf(file, "-- Command structure:\n") <= 0) return false;
  if (fprintf(file, "-- clear all\n") <= 0) return false;
  if (fprintf(file, "-- add [TODO Name]\n\n") <= 0) return false;
  return true;
}

void free_todo(Todo *todo) {
  free(todo->data);
  free(todo);
}

/// FILE OPERATIONS
char *concatenate_paths(const char *directory, const char *relative) {
  unsigned int directory_length = strlen(directory);
  unsigned int relative_length = strlen(relative);

  char *full_path = malloc(directory_length + 1 + relative_length + 1);
  if (!full_path) return NULL;
  sprintf(full_path, "%s/%s", directory, relative);
  return full_path;
}

char *get_path_from_variable(const char *variable, const char *path_from_directory) {
  const char *directory_path = getenv(variable);
  if (!directory_path) return NULL;

  return concatenate_paths(directory_path, path_from_directory);
}

bool save_string_to_binary_file(FILE *file, char *str) {
  unsigned int size = strlen(str);
  if (fwrite(&size, sizeof(unsigned int), 1, file) != 1) return false;
  if (fwrite(str, size, 1, file) != 1) return false;
  return true;
}

bool load_string_from_binary_file(FILE *file, char **str) {
  unsigned int size;
  if (fread(&size, sizeof(unsigned int), 1, file) != 1) return false;
  *str = malloc(size+1);
  if (fread(*str, size, 1, file) != 1) return false;
  (*str)[size] = '\0';
  return true;
}

bool save_todo_to_binary_file(FILE *file, Todo *todo) {
  if (!save_string_to_binary_file(file, todo->data)) return false;
  return true;
}

void *load_todo_from_binary_file(FILE *file) {
  Todo *todo = malloc(sizeof(Todo));
  if (!todo) abort();
  if (!load_string_from_binary_file(file, &todo->data)) return false;
  return todo;
}

bool save_todo_to_text_file(FILE *file, Todo *todo) {
  if (fprintf(file, "add %s\n",todo->data) <= 0) return false;
  return true;
}

void save_file() {
  char *path = get_path_from_variable("HOME", SAVE_PATH);
  FILE *save_file = fopen(path, "wb");
  free(path);
  if (!save_file) return;

  list_save_to_bfile(todo_list, (bool (*)(FILE *, void *)) save_todo_to_binary_file, save_file);

  fclose(save_file);
  return;
}

void load_file() {
  if (!list_is_empty(todo_list)) abort();
  char *path = get_path_from_variable("HOME", SAVE_PATH);
  FILE *save_file = fopen(path, "rb");
  free(path);
  if (!save_file) return;

  list_load_from_bfile(&todo_list, load_todo_from_binary_file, save_file);

  fclose(save_file);
  return;
}

/// Functionality
Action_return add_todo(Input *input) {
  Todo *new = malloc(sizeof(Todo));
  if (!new) return ACTION_RETURN(RETURN_ERROR_AND_EXIT, "No more memory");
  new->data = next_token(input, 0);
  if (!new->data) {
    free(new);
    return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  }
  list_append(&todo_list, new);
  return ACTION_RETURN(RETURN_SUCCESS, "");
}

Action_return remove_todo(Input *input) {
  char *pos_str = next_token(input, 0);
  if (!pos_str) return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  unsigned int pos = atoi(pos_str);
  free(pos_str);

  if (pos == 0 || pos > list_size(todo_list)) return ACTION_RETURN(RETURN_ERROR, "Invalid Position");

  free_todo(list_remove(&todo_list, pos-1));
  return ACTION_RETURN(RETURN_SUCCESS, "");
}

Action_return move_todo(Input *input) {
  char *pos_origin_str = next_token(input, ' ');
  if (!pos_origin_str) return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  unsigned int pos_origin = atoi(pos_origin_str);
  free(pos_origin_str);

  char *pos_destination_str = next_token(input, 0);
  if (!pos_destination_str) return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  unsigned int pos_destination = atoi(pos_destination_str);
  free(pos_destination_str);

  if (pos_origin == 0 || pos_origin > list_size(todo_list)) return ACTION_RETURN(RETURN_ERROR, "Invalid origin position");
  if (pos_destination == 0 || pos_destination > list_size(todo_list)) return ACTION_RETURN(RETURN_ERROR, "Invalid destination position");
  if (pos_destination == pos_origin) return ACTION_RETURN(RETURN_INFO, "Moving to the same position");

  Todo *todo = list_remove(&todo_list, pos_origin-1);
  // if (pos_origin < pos_destination) pos_destination--;
  list_insert_at(&todo_list, todo, pos_destination-1);
  return ACTION_RETURN(RETURN_SUCCESS, "");
}

Action_return edit_todo(Input *input) {
  char *pos_str = next_token(input, ' ');
  if (!pos_str) return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  unsigned int pos = atoi(pos_str);
  free(pos_str);

  if (pos == 0 || pos > list_size(todo_list)) return ACTION_RETURN(RETURN_ERROR, "Invalid Position");

  char *new_text = next_token(input, 0);
  if (!new_text) return ACTION_RETURN(RETURN_ERROR, "Empty new text.");

  Todo *todo = list_get(todo_list, pos-1);
  free(todo->data);
  todo->data = new_text;
  return ACTION_RETURN(RETURN_SUCCESS, "");
}

Action_return clear_todos(Input *input) {
  char *confirmation = next_token(input, 0);
  if (!confirmation || strcmp(confirmation, "all")) {
    free(confirmation);
    return ACTION_RETURN(RETURN_ERROR, "Command malformed");
  }
  free(confirmation);

  list_destroy(&todo_list, (void (*)(void *))free_todo);
  return ACTION_RETURN(RETURN_SUCCESS, "");
}

Functionality todo_list_functionality[] = {
  { "a", "add", add_todo },
  { "rm", "" , remove_todo },
  { "mv" , "move", move_todo },
  { "e" , "edit", edit_todo },
  { "" , "clear", clear_todos },
};

unsigned int todo_list_functionality_count() {
  return sizeof(todo_list_functionality) / sizeof(Functionality);
}
